// ITEM ACTION TYPES
export const GET_ITEMS_START = 'GET_ITEMS_START';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const SORT_ITEMS_START = 'SORT_ITEMS_START';
export const SORT_ITEMS_SUCCESS = 'SORT_ITEMS_SUCCESS';
export const SET_SELECTED = 'SET_SELECTED';

export const ADD_ITEM = 'ADD_ITEM';

export const DELETE_ITEM = 'DELETE_ITEM';